name: Manual Build, Test, and Publish 🚀

on: workflow_dispatch

# ensures that only one workflow task per branch/environment will run at a time
# avoids race conditions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: https://npm.pkg.github.com/
          scope: '@alfergus0n'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # cache remains for up to 7 days after last access
      - name: Building and Caching Packages
        uses: actions/cache@v3
        id: cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies If node_modules Cache Not Found
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      # todo: run test here  
      - name: Release Packages
        run: npm run changeset-publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Release Packages
      #   uses: changesets/action@v1
      #   with:
      #     publish: npm run changeset-publish
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      # - name: Push tags
      #   run: git push --follow-tags